version: '3'

services:
  flight-service:
    image: flight-service
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 3001:3001
    env_file:
      - .env
    environment:
      - MONGO_CONNECTION=mongodb://mongo:27017
      - MONGO_DB=flight-service
    networks:
      - backend-network
    depends_on:
      - redis
      - mongo
    command: ["sh", "-c", "npm run migrate && npm run start"]

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - backend-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
